# Generated by Django 2.1.4 on 2018-12-04 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('chosen', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('customer', models.CharField(max_length=255)),
                ('bid_sum', models.FloatField()),
                ('created', models.DateField()),
                ('deadline', models.DateField()),
                ('loaded', models.DateField(default=django.utils.timezone.now)),
                ('on_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
